export const NIGHT_CAPABILITIES = Object.freeze([
  { id: 'chat', live: true, description: 'General conversation, reasoning, drafting and question answering.' },
  { id: 'web.search', live: true, description: 'Search the live web and answer with current information.' },
  { id: 'summarize', live: true, description: 'Summarize supplied text or conversation context.' },
  { id: 'translate', live: true, description: 'Detect the source language and translate to English by default.' },
  { id: 'rewrite', live: true, description: 'Rewrite text for tone, clarity, brevity or style.' },
  { id: 'explain', live: true, description: 'Explain text, concepts or messages clearly.' },
  { id: 'guide', live: true, description: 'Explain which Night feature or command can do a requested task.' },
  { id: 'table.render', live: false, description: 'Create structured comparison tables; image by default, PDF on request.' },
  { id: 'pdf.render', live: true, description: 'Generate text-based PDF reports and history exports.' },
  { id: 'image.generate', live: false, description: 'Generate images from prompts using configured image provider.' },
  { id: 'image.understand', live: false, description: 'Understand screenshots and images, including OCR and descriptions.' },
  { id: 'image.edit', live: false, description: 'Crop, resize, redact, enhance or otherwise edit images.' },
  { id: 'ocr', live: false, description: 'Extract text from images and document pages.' },
  { id: 'transcribe', live: false, description: 'Transcribe voice notes, audio and video.' },
  { id: 'tts', live: false, description: 'Turn text into speech.' },
  { id: 'sticker.create', live: false, description: 'Turn images, GIFs and short videos into WhatsApp stickers.' },
  { id: 'sticker.convert', live: false, description: 'Turn stickers back into image, GIF or video.' },
  { id: 'viewonce.open', live: false, description: 'Open owner-authorized view-once media.' },
  { id: 'status.post', live: false, description: 'Post text, image or video WhatsApp Status based on supplied media.' },
  { id: 'status.schedule', live: false, description: 'Schedule a WhatsApp Status for later.' },
  { id: 'storage.save', live: false, description: 'Save files, media, links, notes and messages into the private library.' },
  { id: 'storage.find', live: false, description: 'Search saved content by keyword or meaning.' },
  { id: 'storage.recent', live: false, description: 'Show recently saved items.' },
  { id: 'storage.archive', live: false, description: 'Archive saved items.' },
  { id: 'notes', live: false, description: 'Create and retrieve private notes and journal entries.' },
  { id: 'group.catchup', live: false, description: 'Summarize what happened in an observed or allowed group.' },
  { id: 'group.observe', live: false, description: 'Privately index an owner-approved group without replying there.' },
  { id: 'action.extract', live: false, description: 'Extract tasks, deadlines, decisions and owners from conversations or documents.' },
  { id: 'reply.draft', live: true, description: 'Draft a reply in the requested tone without sending automatically.' },
  { id: 'message.semantic_search', live: false, description: 'Find messages by meaning rather than exact wording.' },
  { id: 'link.read', live: true, description: 'Read and summarize public links using web search/visit tools.' },
  { id: 'document.brain', live: false, description: 'Summarize, question-answer and transform PDFs and office documents.' },
  { id: 'conversation.document', live: false, description: 'Turn a conversation into notes, checklist, report or document.' },
  { id: 'pinterest', live: false, description: 'Find Pinterest media.' },
  { id: 'meme', live: false, description: 'Find memes.' },
  { id: 'darkmeme', live: false, description: 'Find dark memes.' },
  { id: 'gif.search', live: false, description: 'Find reaction GIFs and animated media.' },
  { id: 'anime', live: false, description: 'Explore trending, popular, airing and searchable anime.' },
  { id: 'manga', live: false, description: 'Explore trending, popular, recent and searchable manga.' },
  { id: 'release.watch', live: false, description: 'Watch for new anime episodes, manga chapters, releases or page changes.' },
  { id: 'download.helper', live: false, description: 'Fetch supported public media and metadata.' },
  { id: 'poll', live: false, description: 'Create a WhatsApp poll from natural language.' },
  { id: 'qr', live: false, description: 'Generate or scan QR codes and barcodes.' },
  { id: 'reminder', live: false, description: 'Create one-off or recurring reminders.' },
  { id: 'scheduled.message', live: false, description: 'Schedule owner-approved outbound messages.' },
  { id: 'todo', live: false, description: 'Create and manage private tasks.' },
  { id: 'chess', live: false, description: 'Play chess interactively.' },
  { id: 'trivia', live: false, description: 'Play trivia interactively.' },
  { id: 'hangman', live: false, description: 'Play hangman.' },
  { id: 'wordchain', live: false, description: 'Play a word-chain game.' },
  { id: 'wouldyourather', live: false, description: 'Play would-you-rather.' },
  { id: 'usage', live: true, description: 'Show Night usage statistics.' },
  { id: 'history', live: true, description: 'Show or export command and AI activity history.' },
  { id: 'costs', live: false, description: 'Track AI provider usage and configured spending caps.' },
  { id: 'diagnostics', live: true, description: 'Inspect Night command/module errors and session health.' },
  { id: 'workflow', live: false, description: 'Chain multiple capabilities into an owner-requested workflow.' }
]);

export function capabilitySummary({ liveOnly = false } = {}) {
  return NIGHT_CAPABILITIES
    .filter(item => !liveOnly || item.live)
    .map(item => `${item.id}: ${item.description}${item.live ? '' : ' [wired later]'}`)
    .join('\n');
}
