export const NIGHT_CAPABILITIES = Object.freeze([
  { id: 'chat', live: true, description: 'General conversation, reasoning, drafting and question answering.' },
  { id: 'web.search', live: true, description: 'Search the live web and answer with current information.' },
  { id: 'summarize', live: true, description: 'Summarize supplied text or conversation context.' },
  { id: 'translate', live: true, description: 'Detect the source language and translate to English by default.' },
  { id: 'rewrite', live: true, description: 'Rewrite text for tone, clarity, brevity or style.' },
  { id: 'explain', live: true, description: 'Explain text, concepts or messages clearly.' },
  { id: 'guide', live: true, description: 'Explain which Night feature or command can do a requested task.' },
  { id: 'table.render', live: true, description: 'Create structured comparison tables; image by default, PDF on request.' },
  { id: 'pdf.render', live: true, description: 'Generate text-based PDF reports and history exports.' },
  { id: 'image.generate', live: true, description: 'Generate images from prompts when the configured image provider is available.' },
  { id: 'image.understand', live: true, description: 'Understand screenshots and images, including OCR and descriptions, when Vision is configured.' },
  { id: 'image.edit', live: true, description: 'Resize, compress and redact images deterministically.' },
  { id: 'ocr', live: true, description: 'Extract text from images using the configured vision service.' },
  { id: 'transcribe', live: true, description: 'Transcribe voice notes, audio and video using the configured speech service.' },
  { id: 'tts', live: true, description: 'Turn text into speech using the configured speech service.' },
  { id: 'sticker.create', live: true, description: 'Turn supported images and short media into WhatsApp stickers.' },
  { id: 'sticker.convert', live: true, description: 'Turn stickers back into image or video-compatible media.' },
  { id: 'viewonce.open', live: true, description: 'Open owner-authorized view-once media by replying to it.' },
  { id: 'status.post', live: true, description: 'Post text, image, audio or video WhatsApp Status based on supplied media.' },
  { id: 'status.schedule', live: true, description: 'Schedule text, image or video WhatsApp Status for later.' },
  { id: 'storage.save', live: true, description: 'Save messages and private library items.' },
  { id: 'storage.find', live: true, description: 'Search saved content.' },
  { id: 'storage.recent', live: true, description: 'Show recently saved items.' },
  { id: 'storage.archive', live: true, description: 'Archive saved items.' },
  { id: 'notes', live: true, description: 'Create and retrieve private notes.' },
  { id: 'group.catchup', live: true, description: 'Summarize stored messages from an observed or allowed group.' },
  { id: 'group.observe', live: true, description: 'Privately index an owner-approved group without enabling Night replies there.' },
  { id: 'action.extract', live: true, description: 'Extract tasks, deadlines, decisions and owners from supplied text or stored conversation context.' },
  { id: 'reply.draft', live: true, description: 'Draft a reply in the requested tone without sending automatically.' },
  { id: 'message.semantic_search', live: true, description: 'Find stored messages by meaning rather than exact wording.' },
  { id: 'link.read', live: true, description: 'Read and summarize public links using web search.' },
  { id: 'document.brain', live: true, description: 'Summarize, question-answer and transform supported PDFs and office documents.' },
  { id: 'conversation.document', live: true, description: 'Turn conversation text into notes, a checklist, report or document.' },
  { id: 'pinterest', live: true, description: 'Find useful Pinterest results using web search.' },
  { id: 'meme', live: true, description: 'Find memes.' },
  { id: 'darkmeme', live: true, description: 'Find dark memes.' },
  { id: 'gif.search', live: true, description: 'Find reaction GIFs using the configured GIF provider.' },
  { id: 'anime', live: true, description: 'Explore trending, popular, airing and searchable anime.' },
  { id: 'manga', live: true, description: 'Explore trending, popular, recent and searchable manga.' },
  { id: 'release.watch', live: true, description: 'Watch anime, manga or a web state for changes and notify the owner.' },
  { id: 'download.helper', live: true, description: 'Fetch supported public files from direct public URLs.' },
  { id: 'poll', live: true, description: 'Create a WhatsApp poll.' },
  { id: 'qr', live: true, description: 'Generate and scan QR codes.' },
  { id: 'reminder', live: true, description: 'Create one-off reminders.' },
  { id: 'scheduled.message', live: true, description: 'Schedule owner-approved outbound messages.' },
  { id: 'todo', live: true, description: 'Create and manage private tasks.' },
  { id: 'chess', live: true, description: 'Play chess interactively.' },
  { id: 'tictactoe', live: true, description: 'Play tic-tac-toe interactively.' },
  { id: 'trivia', live: true, description: 'Play trivia interactively.' },
  { id: 'hangman', live: true, description: 'Play hangman.' },
  { id: 'wordchain', live: true, description: 'Play a word-chain game.' },
  { id: 'wouldyourather', live: true, description: 'Play would-you-rather.' },
  { id: 'usage', live: true, description: 'Show Night usage statistics.' },
  { id: 'history', live: true, description: 'Show or export command and AI activity history.' },
  { id: 'costs', live: true, description: 'Track AI provider usage and configured spending caps.' },
  { id: 'diagnostics', live: true, description: 'Inspect Night command/module errors and session health.' },
  { id: 'workflow', live: true, description: 'Chain a bounded set of owner-requested capabilities into a safe workflow.' }
]);

export function capabilitySummary({ liveOnly = false } = {}) {
  return NIGHT_CAPABILITIES
    .filter(item => !liveOnly || item.live)
    .map(item => `${item.id}: ${item.description}${item.live ? '' : ' [wired later]'}`)
    .join('\n');
}
